### PR TITLE
Tests with Karma & Jasmine

### PR DESCRIPTION
**Pull request by Nelrohd**
No more cucumber.
Now using karma and jasmine.
Wrote initial tests for widgets.js, widget-view.js and
widget-gridview.js.
Changed template inside gridview so its internal

### CODE REVIEW

**Comment by Nelrohd** [comment]
@FredFaust For you :) Btw your branch is named tests-cucumber ^^

**Comment by jffaust** [comment]
@Nelrohd Yeah I know lol, is it possible to rename a branch or I need to create a new and delete this one ?

**Comment by Nelrohd** [comment]
Just do it inside your git repo 

```
git branch -m <newname>
```

**Comment by jffaust** [comment]
I did the command, everything seems fin in the Github desktop app but the changes doesn't appear on the website even after a sync/publish :

http://puu.sh/iL2Sm/c7c9348982.png

**Comment by Nelrohd** [comment]
@FredFaust 

```
git push -f origin <branch-name>
```

**Comment by jffaust** [comment]
All the tests are now on the branch `tests-jasmine`

**Pull request closed without merging**
